mod private;

use crate::{DataFormat, Lowerable, Lowered};
use private::{Bounds, LowerableCompoundExtDef, Content, Sealed};

pub use cu29_derive::LowerableCompound;

pub struct FieldDescriptor<FieldType> {
    pub name: &'static str,
    pub default: Option<FieldType>,
}
impl<FieldType> FieldDescriptor<FieldType> {
    pub const fn no_default(name: &'static str) -> Self {
        Self {
            name,
            default: None,
        }
    }
}

pub struct VariantDescriptor<Struct> {
    pub name: &'static str,
    pub fields: Struct,
}
impl<Struct> VariantDescriptor<Struct> {
    pub const fn new(name: &'static str, fields: Struct) -> Self {
        Self { name, fields }
    }
}

pub type Desc<C> = <C as Content>::Descriptor;

/// A compound type (typically comprising multiple fields).
///
/// Implementations of this trait are generated by the [`LowerableCompound`][derive@LowerableCompound]
/// derive macro, which is the recommended way to implement it.  Explicit implementations are
/// likely only to be defined locally in this crate, for upstream library types.
///
/// Consumers of this trait should typically use its [`LowerableCompound`] subtrait instead, which
/// avoids any need to name the `'this` lifetime parameter.  The `ImplicitBounds` parameter
/// exists only to facilitate that (and in any event cannot be named owing to its `Sealed`
/// constraint: the default of `Bounds<'this, Self>` is the only type that the parameter can
/// or should be).  In effect this enables the associated `Descriptor` type to be generic
/// over the `'this` lifetime parameter in a usable way.
///
/// See [The Better Alternative to Lifetime GATs] for more information.
///
/// [The Better Alternative to Lifetime GATs]: https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats
pub trait LowerableCompoundDef<'this, ImplicitBounds: Sealed = Bounds<'this, Self>> {
    /// The intermediate representation into which this compound type is lowered by
    /// [`LowerableCompoundDef::intermediate`].  Due to this trait's `'this` lifetime parameter,
    /// the intermediate representation can borrow from the compound type itself.
    ///
    /// Implementors may find it convenient to use the [`Cons`] (and, for enums, also the
    /// [`Alt`]) macros to construct the intermediate representation.
    ///
    /// [`Cons`]: crate::Cons
    /// [`Alt`]: crate::Alt
    type Intermediate: Content;

    /// Descriptors for the fields in this compound type's intermediate representation.
    ///
    /// Implementors may find it convenient to use the [`cons`] macro to construct the list.
    ///
    /// [`cons`]: crate::cons
    const DESCRIPTOR: Desc<Self::Intermediate>;

    /// Marshals a value of this compound type into its intermediate representation.
    ///
    /// Implementors may find it convenient to use the [`cons`] (and, for enums, also the
    /// [`alt`]) macros to construct a value of the intermediate representation.
    ///
    /// [`cons`]: crate::cons
    /// [`alt`]: crate::alt
    fn intermediate(&'this self) -> Self::Intermediate;
}

/// [`Lowerable::Sigil`] sigil for [`LowerableCompound`]s.
pub enum Compound {}

/// A compound type (typically comprising multiple fields).
///
/// Implementations of this trait are generated by the [`LowerableCompound`][derive@LowerableCompound]
/// derive macro, which is the recommended way to implement it.  Explicit implementations are
/// likely only to be defined locally in this crate, for upstream library types.
///
/// When such a compound type is required in a particular [`DataFormat`], consumers should
/// typically use this trait's [`LowerableCompoundExt<Format>`] subtrait instead as that provides
/// the schema and encodable fields for that format.
pub trait LowerableCompound:
    Lowerable<Sigil = Compound> + for<'this> LowerableCompoundDef<'this>
{
}
impl<T: Lowerable<Sigil = Compound> + for<'this> LowerableCompoundDef<'this>> LowerableCompound for T {}

/// A blanket-implemented extension trait that (through its unnameable `LowerableCompoundExtDef`
/// supertrait) provides convenient access to the schema of a compound type's fields, and the
/// list of encodable field values.
pub trait LowerableCompoundExt<Format: DataFormat>
where
    Self: LowerableCompound + for<'this> LowerableCompoundExtDef<'this, Format>,
{
}
impl<Format: DataFormat, T> LowerableCompoundExt<Format> for T where
    T: LowerableCompound + for<'this> LowerableCompoundExtDef<'this, Format>
{
}

/// Proxy trait for implementing [`Lowers<T>`] when `T` is a [`LowerableCompound`].
///
/// [`DataFormat`] definers will typically want to implement this trait for generic `T`, to
/// describe how that format encodes [`LowerableCompound`]s.
///
/// Consumers will usually want to use [`Lowers<T>`] instead, which is blanket implemented
/// for implementers of this trait (but also for other [`Lowerable`]s).
///
/// [`Lowers<T>`]: crate::Lowers<T>
pub trait LowersCompound<T: ?Sized + Lowerable<Sigil = Compound>>: DataFormat {
    type LoweredCompound<'a>: Lowered<Self>
    where
        T: 'a;
    fn lower_compound(t: &T) -> Self::LoweredCompound<'_>;
}
